# -*- coding: utf-8 -*-
"""generate_image_txt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ncvH5Ybv4GRVVwDOcFF0pqRVlPBAkemg
"""

import os

# 設定圖片文件夾的路徑
image_folder_path = '/content/drive/MyDrive/fpop_with_convGRU/Underwater/data/train'

# 獲取該文件夾中的所有圖片文件名
image_files = [file for file in os.listdir(image_folder_path) if file.endswith('.png')]

# 設定要生成的 txt 文件的路徑
txt_file_path = '/content/drive/MyDrive/fpop_with_convGRU/train_list.txt'

# 寫入文件名（去掉副檔名）到 txt 文件中，停止在第200個資料
with open(txt_file_path, 'w') as file:
    for i, image_file in enumerate(image_files):
        # 使用 os.path.splitext() 將副檔名分離
        file_name_without_extension, _ = os.path.splitext(image_file)
        file.write(file_name_without_extension + '\n')

        # 檢查是否已經寫入了前200個資料
        if i + 1 == 200:
            break

print(f'Txt file {txt_file_path} generated successfully.')